### ISSUE TITLE
one problem I see....

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/GWASCatalogSearchDB#2] opened 2023-05-27 16:26 UTC
Hi Rafael,
  as near as I can tell, in this DB the Direct count is correct - that is the number of phenotypes that map to the EFO label,
but inherited is the sum of those mapping directly + those inherited. 
  I am sort of happy either way, but my interpretation of the English semantics is that inherited should not include the direct mappers.
  And I could be wrong, but for my code I get things like this:
<img width="770" alt="image" src="https://github.com/ccb-hms/GWASCatalogSearchDB/assets/12532483/21efb164-951a-4ec3-9879-e6cda3a6c00f">
 and then searching for all (include inherited) just gets me the number of records under inherited...

**Comment by rsgoncalves** [comment] 2023-05-30 13:57
Thank you for bringing this up. The inherited count is indeed currently the sum, by mistake — it will be fixed in a next version, such that we get the total by summing direct + inherited.

**Comment by rsgoncalves** [comment] 2023-05-31 13:58
The issue is fixed via 6162766. The latest DB (https://github.com/ccb-hms/GWASCatalogSearchDB/releases/tag/v0.2.0) has updated counts.

**Closed as completed by rsgoncalves** 2023-05-31 13:58 UTC
